Added netcdf
NCAR/music-box pull request #273
Opened 2024-11-01 22:35 UTC by montythind

CMD argument is available to define type of file.
Units have been added to csv file header
units added to header in netcdf

close #238

2024-11-04 15:30 UTC, K20shores commented on src/acom_music_box/music_box.py
> +                    'time': 's'
```suggestion
                    'ENV.temperature': 'K',
                    'ENV.pressure': 'Pa',
                    'ENV.number_density_air': 'kg -m3',
                    'time': 's'
```

We should be outputting in pascals, not kilopascals

2024-11-04 15:32 UTC, K20shores requested changes

2024-11-04 15:32 UTC, K20shores commented on src/acom_music_box/music_box.py
> +                    f"{col} (mol m-3)" if col.startswith('CONC.') else col
```suggestion
                    f"{col}.({unit_mapping[col]})" if col in unit_mapping else 
                    f"{col}.(mol m-3)" if col.startswith('CONC.') else col
```

We prefer period separated titles

2024-11-04 15:32 UTC, K20shores commented on src/acom_music_box/music_box.py
You've added the header units output only when we output to csv. Please add the header units always so that the results that get printed to the terminal also have units

2024-11-06 14:47 UTC, K20shores requested changes
Some minor changes in the code. Would you also please add some tests?

2024-11-06 14:47 UTC, K20shores commented on src/acom_music_box/data_output.py
> +    def ensure_output_path(self):
```suggestion
    def _ensure_output_path(self):
```

Since this is a private function, we should prefix it with an underscores.

2024-11-06 14:47 UTC, K20shores commented on src/acom_music_box/data_output.py
> +    def append_units_to_columns(self):
```suggestion
    def _append_units_to_columns(self):
```

Since this is a private function, we should prefix it with an underscores.

2024-11-06 14:47 UTC, K20shores commented on src/acom_music_box/data_output.py
> +    def convert_to_netcdf(self):
```suggestion
    def _convert_to_netcdf(self):
```
Since this is a private function, we should prefix it with an underscores.

2024-11-06 14:47 UTC, K20shores commented on src/acom_music_box/music_box.py
>          df = pd.DataFrame(output_array[1:], columns=output_array[0])
```suggestion
        return pd.DataFrame(output_array[1:], columns=output_array[0])
```

Let's just return the results directly now

2024-11-06 14:47 UTC, K20shores commented on src/acom_music_box/music_box.py
>          return df
```suggestion
```

In accordance with the above comment

2024-11-06 14:47 UTC, K20shores commented on src/acom_music_box/data_output.py
> +        }
Please add a docstring to the `DataOutput` class describing its purpose and use. Also, please add a docstring to `__init__` describing the arguments. I don't think we've standardized our documentation yet, but we should strive for [numpy-style docstrings](https://numpydoc.readthedocs.io/en/latest/format.html). If you notice, those can also include examples in the comments. Please attempt to add an example usage in the docstring for `DataOutput`

2024-11-07 14:10 UTC, K20shores approved these changes

2024-11-07 14:19 UTC, K20shores requested changes
Please add instructions to the readme that list how to output either csv, netcdf, or printing the csv to the screen

2024-11-07 18:46 UTC, K20shores requested changes
If you run this

`music_box -e Analytical --output-format netcdf`

output is printed to the screen as csv data. There is not a printable netcdf format since it's a binary format. So, when the output is netcdf and no output path is given, I think we need to output anyway. Choose a default filename (maybe `results`, this would also close https://github.com/NCAR/music-box/issues/237) and set the suffix to .nc or .csv based on the output format. What do you think?

2024-11-08 20:04 UTC, K20shores approved these changes

2024-11-08 20:04 UTC, K20shores submitted a review, later dismissed

2024-11-08 20:29 UTC, boulderdaze approved these changes
Looks good! I just have a minor request but it shouldn't prevent your PR from being merged.

2024-11-08 20:29 UTC, boulderdaze commented on src/acom_music_box/music_box.py
>              callback (function, optional): A callback function that is called after each time step. Defaults to None. The callback will take the most recent results, the current time, conditions, and
Could you make multiple lines instead of one long line for the description? This will help make it easier to read.

2024-11-08 20:36 UTC, boulderdaze commented on README.md
> +Output can be saved to a file in csv file to output.csv when no output path is given but --output-format is csv
Would it be possible to add backticks around the options such as `--output-format`, so they appears clearer?
Output can be saved to a file in csv file to output.csv when no output path is given but `--output-format` is csv

2024-11-11 21:52 UTC, mattldawson approved these changes
nice!

2024-11-12 16:38 UTC, mattldawson approved these changes
looks good!

2024-11-12 16:47 UTC, boulderdaze approved these changes

2024-11-12 16:53 UTC, K20shores approved these changes

2024-11-12 17:05 UTC, merged